import { red } from '@mui/material/colors';
import { token } from '../color-tokens';

export const light = {
  common: {
    black: '#000',
    white: '#fff',
  },
  type: 'light',
  primary: {
    main: token.main_blue,
    light: token.light_blue_main,
    dark: token.main_blue,
    contrastText: '#fff',
  },
  secondary: {
    main: token.main_blue_background,
    light: token.light_blue_main,
    dark: token.main_blue_background,
    contrastText: '#fff',
  },
  error: {
    light: red[500],
    main: red[500],
    dark: '#d85a5a',
    contrastText: '#fff',
  },
  warning: {
    main: '#ffcc00',
    light: '#ffb547',
    dark: '#c77700',
    contrastText: '#fff',
  },
  info: {
    main: '#7bd3ff',
    light: '#c7e7fe',
    dark: '#7bd3ff',
    contrastText: '#fff ',
  },
  success: {
    main: '#37c8aa',
    light: '#cbfff5',
    dark: '#37c8aa',
    contrastText: '#fff',
  },
  grey: {
    50: '#f6f6f8',
    100: '#f2f2f6',
    200: '#f2f2f6',
    300: '#e6e6ed',
    400: '#8686a5',
    500: '#8686a5',
    600: '#0e0e4c',
    700: '#0e0e4c',
    800: '#0e0e4c',
    900: '#0e0e4c',
    A100: '#e6e6ed',
    A200: '#b6b6c9',
    A400: '#8686a5',
    A700: '#3e3e6f',
  },
  text: {
    primary: token.text_light_grey,
    secondary: token.text_light_grey,
    disabled: token.text_light_grey,
    hint: token.text_light_grey,
  },
  divider: token.grey_border,
  background: {
    paper: '#fff',
    default: token.background,
  },
  action: {
    active: '#8686a5',
    hover: '#f2f2f6',
    hoverOpacity: 0.04,
    selected: '#f6f6f8',
    selectedOpacity: 0.08,
    disabled: '#8686a5',
    disabledBackground: '#e6e6ed',
    disabledOpacity: 0.38,
    focus: '#f2f2f6',
    focusOpacity: 0.12,
    activatedOpacity: 0.12,
  },
};
