import { ThemeRegistry } from '@shared-theme';
import './global.css';
import { StyledComponentsRegistry } from './registry';
import {
  AppBar,
  Box,
  Divider,
  Drawer,
  Link,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Toolbar,
  Typography,
} from '@mui/material';
import SpaceDashboardOutlinedIcon from '@mui/icons-material/SpaceDashboardOutlined';
import CorporateFareRoundedIcon from '@mui/icons-material/CorporateFareRounded';
import SentimentSatisfiedAltOutlinedIcon from '@mui/icons-material/SentimentSatisfiedAltOutlined';
import TabletAndroidRoundedIcon from '@mui/icons-material/TabletAndroidRounded';
import AccountCircleOutlinedIcon from '@mui/icons-material/AccountCircleOutlined';
import HubOutlinedIcon from '@mui/icons-material/HubOutlined';
import DashboardIcon from '@mui/icons-material/Dashboard';
import SettingsIcon from '@mui/icons-material/Settings';
import SupportIcon from '@mui/icons-material/Support';
import LogoutIcon from '@mui/icons-material/Logout';

const DRAWER_WIDTH = 240;

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

const LINKS = [
  { text: 'Dashboard', href: '/', icon: SpaceDashboardOutlinedIcon },
  {
    text: 'Organisation',
    href: '/organisation',
    icon: CorporateFareRoundedIcon,
  },
  {
    text: 'Locations',
    href: '/starred',
    icon: SentimentSatisfiedAltOutlinedIcon,
  },
  { text: 'Kiosks', href: '/tasks', icon: TabletAndroidRoundedIcon },
  { text: 'Devices', href: '/tasks', icon: AccountCircleOutlinedIcon },
  { text: 'Users', href: '/tasks', icon: HubOutlinedIcon },
];

const PLACEHOLDER_LINKS = [
  { text: 'Settings', icon: SettingsIcon },
  { text: 'Support', icon: SupportIcon },
  { text: 'Logout', icon: LogoutIcon },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeRegistry>
            <AppBar position="fixed" sx={{ zIndex: 2000 }}>
              <Toolbar sx={{ backgroundColor: 'background.paper' }}>
                <DashboardIcon
                  sx={{ color: '#444', mr: 2, transform: 'translateY(-2px)' }}
                />
                <Typography variant="h6" noWrap component="div" color="black">
                  Next.js App Router
                </Typography>
              </Toolbar>
            </AppBar>
            <Drawer
              sx={{
                width: DRAWER_WIDTH,
                flexShrink: 0,
                '& .MuiDrawer-paper': {
                  width: DRAWER_WIDTH,
                  boxSizing: 'border-box',
                  top: ['48px', '56px', '64px'],
                  height: 'auto',
                  bottom: 0,
                },
              }}
              variant="permanent"
              anchor="left"
            >
              <Divider />
              <List>
                {LINKS.map(({ text, href, icon: Icon }) => (
                  <ListItem key={href} disablePadding>
                    <ListItemButton component={Link} href={href}>
                      <ListItemIcon>
                        <Icon />
                      </ListItemIcon>
                      <ListItemText primary={text} />
                    </ListItemButton>
                  </ListItem>
                ))}
              </List>
              <Divider sx={{ mt: 'auto' }} />
              <List>
                {PLACEHOLDER_LINKS.map(({ text, icon: Icon }) => (
                  <ListItem key={text} disablePadding>
                    <ListItemButton>
                      <ListItemIcon>
                        <Icon />
                      </ListItemIcon>
                      <ListItemText primary={text} />
                    </ListItemButton>
                  </ListItem>
                ))}
              </List>
            </Drawer>
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                bgcolor: 'background.default',
                ml: `${DRAWER_WIDTH}px`,
                mt: ['48px', '56px', '64px'],
                p: 3,
              }}
            >
              {children}
            </Box>
          </ThemeRegistry>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
